apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lcc-engine
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
  - path: environment-patch.yaml
  - path: pdb-patch.yaml
