apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: permit-token-signing-key
  namespace: lcc-engine
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: permit-token-signing-key
  data:
    - secretKey: signing_key
      remoteRef:
        key: lcc/compliance/permit_signing_key
