apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: lcc-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
  data:
    - secretKey: lcc_app_password
      remoteRef:
        key: lcc/postgres/lcc_app
    - secretKey: lcc_audit_writer_password
      remoteRef:
        key: lcc/postgres/lcc_audit_writer
    - secretKey: lcc_readonly_password
      remoteRef:
        key: lcc/postgres/lcc_readonly
