apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-governor
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-gateway
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
spec:
  replicas: 3
