apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: lcc-alertmanager
  namespace: lcc-observability
spec:
  route:
    receiver: 'pagerduty-default'
    group_by: ['alertname', 'severity']
  receivers:
    - name: 'pagerduty-default'
      pagerdutyConfigs:
        - routingKey: ${PAGERDUTY_ROUTING_KEY}
