apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: lcc-prometheus
  namespace: lcc-observability
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  ruleSelector: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
