apiVersion: v1
kind: Namespace
metadata:
  name: lcc-data
  labels:
    app.kubernetes.io/part-of: lcc
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
